/**
 * Practice challenges and scoring weights for Northwind SQL Academy.
 */
window.SQL_ACADEMY_DATA = {
    POINTS_BY_DIFF: { Easy: 10, Medium: 25, Hard: 50, "Super Ultra": 100, "Super Ultra Hard": 150, "Super Ultra Hard Max": 200, "Super Ultra Hard Max Pro": 250, "Super Ultra Hard Max Pro God": 350 },
    STORAGE_KEY: "northwind-sql-academy-progress",
    practiceQuestions: [
        { diff: "Easy", title: "All Customers", text: "Write a query to retrieve all columns from the Customer table.", sql: "SELECT * FROM Customer;" },
        { diff: "Easy", title: "Specific Country", text: "Find the companyName and contactName of all customers located in 'Germany'.", sql: "SELECT companyName, contactName FROM Customer\nWHERE country = 'Germany';" },
        { diff: "Easy", title: "Counting Products", text: "How many products do we have in total? Return a single column named TotalProducts.", sql: "SELECT COUNT(*) AS TotalProducts FROM Product;" },
        { diff: "Easy", title: "Employee Locations", text: "List the firstname, lastname, and city of all employees, sorted alphabetically by their lastname.", sql: "SELECT firstname, lastname, city FROM Employee\nORDER BY lastname ASC;" },
        { diff: "Easy", title: "Discontinued Items", text: "Find all products that have been discontinued (discontinued = '1'). Return the productName.", sql: "SELECT productName FROM Product\nWHERE discontinued = '1';" },
        { diff: "Easy", title: "All Shippers", text: "Retrieve all information about all shipping companies in the database.", sql: "SELECT * FROM Shipper;" },
        { diff: "Easy", title: "Sales Representatives", text: "Find the firstname, lastname, and title of all employees who are a 'Sales Representative'.", sql: "SELECT firstname, lastname, title FROM Employee\nWHERE title = 'Sales Representative';" },
        { diff: "Easy", title: "London Customers", text: "List the companyName, contactName, and city of all customers located in 'London'.", sql: "SELECT companyName, contactName, city FROM Customer\nWHERE city = 'London';" },
        { diff: "Easy", title: "Expensive Products", text: "Find the productName and unitPrice of all products that cost more than $50.00.", sql: "SELECT productName, unitPrice FROM Product\nWHERE unitPrice > 50.00;" },
        { diff: "Easy", title: "Supplier Phonebook", text: "Create a phonebook of suppliers by listing their companyName and phone number.", sql: "SELECT companyName, phone FROM Supplier;" },

        { diff: "Medium", title: "Needs Reordering", text: "Find products that are low in stock. Return productName and unitsInStock where unitsInStock is less than the reorderLevel.", sql: "SELECT productName, unitsInStock, reorderLevel FROM Product\nWHERE unitsInStock < reorderLevel;" },
        { diff: "Medium", title: "Customer & Order Match", text: "List every order's entityId along with the companyName of the customer who placed it. (Requires joining SalesOrder and Customer).", sql: "SELECT o.entityId AS OrderId, c.companyName \nFROM SalesOrder o\nJOIN Customer c ON o.customerId = c.entityId;" },
        { diff: "Medium", title: "Freight Costs", text: "Calculate the total amount of freight paid for all orders sent to 'France'.", sql: "SELECT SUM(freight) AS TotalFreightToFrance \nFROM SalesOrder\nWHERE shipCountry = 'France';" },
        { diff: "Medium", title: "Products by Category", text: "List categoryName and the number of products in each category. (Requires joining Category and Product, and GROUP BY).", sql: "SELECT c.categoryName, COUNT(p.entityId) as ProductCount\nFROM Category c\nJOIN Product p ON c.entityId = p.categoryId\nGROUP BY c.categoryName;" },
        { diff: "Medium", title: "Never Ordered", text: "Find customers who have never placed an order. Return their entityId and companyName.", sql: "SELECT c.entityId, c.companyName\nFROM Customer c\nLEFT JOIN SalesOrder o ON c.entityId = o.customerId\nWHERE o.entityId IS NULL;" },
        { diff: "Medium", title: "Inventory Value", text: "Calculate the total inventory value for each product. Return productName and InventoryValue (unitPrice * unitsInStock).", sql: "SELECT productName, (unitPrice * unitsInStock) AS InventoryValue\nFROM Product;" },
        { diff: "Medium", title: "Average Price per Category", text: "Find the average unitPrice of products in each category. Return categoryName and AveragePrice.", sql: "SELECT c.categoryName, AVG(p.unitPrice) AS AveragePrice\nFROM Category c\nJOIN Product p ON c.entityId = p.categoryId\nGROUP BY c.categoryName;" },
        { diff: "Medium", title: "Orders in 1997", text: "Find all orders placed in the year 1997. Return the entityId and orderDate.", sql: "SELECT entityId, orderDate \nFROM SalesOrder \nWHERE orderDate LIKE '1997%';" },
        { diff: "Medium", title: "Employee Territories", text: "List the firstname and lastname of employees alongside the territorydescription of their assigned territories.", sql: "SELECT e.firstname, e.lastname, t.territorydescription \nFROM Employee e \nJOIN EmployeeTerritory et ON e.entityId = et.employeeId \nJOIN Territory t ON et.territoryCode = t.territoryCode;" },
        { diff: "Medium", title: "Customer Managers", text: "List all customers who have the word 'Manager' anywhere in their contactTitle.", sql: "SELECT companyName, contactTitle \nFROM Customer \nWHERE contactTitle LIKE '%Manager%';" },

        { diff: "Hard", title: "High Value Orders", text: "Find all Orders that had a total value (unitPrice * quantity) greater than $10,000. Ignore discounts for this calculation.", sql: "SELECT orderId, SUM(unitPrice * quantity) AS OrderTotal\nFROM OrderDetail\nGROUP BY orderId\nHAVING SUM(unitPrice * quantity) > 10000;" },
        { diff: "Hard", title: "Top 5 Employees", text: "Who are the top 5 employees by total number of orders processed? Return firstname, lastname, and TotalOrders.", sql: "SELECT e.firstname, e.lastname, COUNT(o.entityId) AS TotalOrders\nFROM Employee e\nJOIN SalesOrder o ON e.entityId = o.employeeId\nGROUP BY e.entityId\nORDER BY TotalOrders DESC\nLIMIT 5;" },
        { diff: "Hard", title: "Revenue by Category", text: "Calculate the total gross revenue (unitPrice * quantity) generated by each Product Category. Sort by highest revenue first.", sql: "SELECT c.categoryName, SUM(od.unitPrice * od.quantity) as TotalRevenue\nFROM Category c\nJOIN Product p ON c.entityId = p.categoryId\nJOIN OrderDetail od ON p.entityId = od.productId\nGROUP BY c.categoryName\nORDER BY TotalRevenue DESC;" },
        { diff: "Hard", title: "Late Shipments", text: "Find orders that were shipped after their requiredDate. Return the order's entityId, orderDate, requiredDate, and shippedDate.", sql: "SELECT entityId AS OrderId, orderDate, requiredDate, shippedDate\nFROM SalesOrder\nWHERE shippedDate > requiredDate;" },
        { diff: "Hard", title: "VIP Customers", text: "Find the total amount of money spent by 'QUICK-Stop' (companyName: QUICK-Stop). Include discount calculation: unitPrice * quantity * (1 - discount).", sql: "SELECT c.companyName, SUM(od.unitPrice * od.quantity * (1 - od.discount)) AS TotalSpent\nFROM Customer c\nJOIN SalesOrder o ON c.entityId = o.customerId\nJOIN OrderDetail od ON o.entityId = od.orderId\nWHERE c.companyName = 'QUICK-Stop'\nGROUP BY c.companyName;" },
        { diff: "Hard", title: "Top 3 Customers", text: "Find the top 3 customers by total amount spent (ignoring discounts). Return companyName and TotalSpent.", sql: "SELECT c.companyName, SUM(od.unitPrice * od.quantity) AS TotalSpent \nFROM Customer c \nJOIN SalesOrder o ON c.entityId = o.customerId \nJOIN OrderDetail od ON o.entityId = od.orderId \nGROUP BY c.companyName \nORDER BY TotalSpent DESC \nLIMIT 3;" },
        { diff: "Hard", title: "Most Popular Product", text: "Find the single product that has been ordered the most in terms of total quantity. Return productName and TotalQuantity.", sql: "SELECT p.productName, SUM(od.quantity) AS TotalQuantity \nFROM Product p \nJOIN OrderDetail od ON p.entityId = od.productId \nGROUP BY p.productName \nORDER BY TotalQuantity DESC \nLIMIT 1;" },
        { diff: "Hard", title: "Managers & Direct Reports", text: "List each employee's firstname and lastname along with their manager's firstname and lastname (requires a self-join).", sql: "SELECT e1.firstname AS EmployeeFirst, e1.lastname AS EmployeeLast, e2.firstname AS ManagerFirst, e2.lastname AS ManagerLast \nFROM Employee e1 \nJOIN Employee e2 ON e1.mgrId = e2.entityId;" },
        { diff: "Hard", title: "Products Never Ordered", text: "Find products that have never been included in any order. Return entityId and productName.", sql: "SELECT p.entityId, p.productName \nFROM Product p \nLEFT JOIN OrderDetail od ON p.entityId = od.productId \nWHERE od.entityId IS NULL;" },
        { diff: "Hard", title: "Orders with Multiple Items", text: "Find orders that contain more than 5 different unique products. Return the orderId and the count of unique products.", sql: "SELECT orderId, COUNT(productId) AS ProductCount \nFROM OrderDetail \nGROUP BY orderId \nHAVING COUNT(productId) > 5;" },

        { diff: "Super Ultra", title: "Sales Leaderboard", text: "Rank employees by their total sales revenue (including discounts). Return firstname, lastname, TotalSales, and their SalesRank.", sql: "SELECT e.firstname, e.lastname, SUM(od.unitPrice * od.quantity * (1 - od.discount)) AS TotalSales, RANK() OVER(ORDER BY SUM(od.unitPrice * od.quantity * (1 - od.discount)) DESC) as SalesRank FROM Employee e JOIN SalesOrder o ON e.entityId = o.employeeId JOIN OrderDetail od ON o.entityId = od.orderId GROUP BY e.entityId;" },
        { diff: "Super Ultra", title: "Most Diverse Buyer", text: "Find the customer who has purchased the highest number of *unique* products. Return companyName and UniqueProducts.", sql: "SELECT c.companyName, COUNT(DISTINCT od.productId) as UniqueProducts FROM Customer c JOIN SalesOrder o ON c.entityId = o.customerId JOIN OrderDetail od ON o.entityId = od.orderId GROUP BY c.entityId ORDER BY UniqueProducts DESC LIMIT 1;" },
        { diff: "Super Ultra", title: "Above Category Average", text: "Find products that are priced higher than the average price of all products in their own category. Return productName, unitPrice, and categoryName.", sql: "SELECT p1.productName, p1.unitPrice, c.categoryName FROM Product p1 JOIN Category c ON p1.categoryId = c.entityId WHERE p1.unitPrice > (SELECT AVG(p2.unitPrice) FROM Product p2 WHERE p2.categoryId = p1.categoryId);" },
        { diff: "Super Ultra", title: "Running Total Freight", text: "Calculate the running total of freight costs for orders placed by the employee with entityId = 1, ordered by orderDate.", sql: "SELECT entityId AS OrderId, orderDate, freight, SUM(freight) OVER(ORDER BY orderDate) as RunningTotal FROM SalesOrder WHERE employeeId = 1;" },
        { diff: "Super Ultra", title: "Employees and Managers", text: "For each employee, return their full name, the total number of orders they processed, and their manager's full name. Include employees without managers.", sql: "SELECT e.firstname || ' ' || e.lastname AS Employee, COUNT(o.entityId) AS TotalOrders, m.firstname || ' ' || m.lastname AS Manager FROM Employee e LEFT JOIN Employee m ON e.mgrId = m.entityId LEFT JOIN SalesOrder o ON e.entityId = o.employeeId GROUP BY e.entityId;" },
        { diff: "Super Ultra", title: "Seafood Haters", text: "Find all customers who have *never* ordered a product from the 'Seafood' category. Return entityId and companyName.", sql: "SELECT entityId, companyName FROM Customer WHERE entityId NOT IN (SELECT o.customerId FROM SalesOrder o JOIN OrderDetail od ON o.entityId = od.orderId JOIN Product p ON od.productId = p.entityId JOIN Category c ON p.categoryId = c.entityId WHERE c.categoryName = 'Seafood');" },
        { diff: "Super Ultra", title: "Whale Customers", text: "Identify customers whose average order value is more than double the overall average order value across all customers. Return companyName and CustAvg.", sql: "WITH OrderTotals AS (SELECT orderId, SUM(unitPrice * quantity * (1-discount)) as OrderValue FROM OrderDetail GROUP BY orderId), OverallAvg AS (SELECT AVG(OrderValue) as AvgVal FROM OrderTotals), CustomerAvg AS (SELECT o.customerId, c.companyName, AVG(ot.OrderValue) as CustAvg FROM SalesOrder o JOIN OrderTotals ot ON o.entityId = ot.orderId JOIN Customer c ON o.customerId = c.entityId GROUP BY o.customerId) SELECT companyName, CustAvg FROM CustomerAvg CROSS JOIN OverallAvg WHERE CustAvg > 2 * AvgVal;" },
        { diff: "Super Ultra", title: "Price Quartiles", text: "Divide all products into 4 quartiles based on their unitPrice using a window function. Return productName, unitPrice, and PriceQuartile.", sql: "SELECT productName, unitPrice, NTILE(4) OVER (ORDER BY unitPrice ASC) as PriceQuartile FROM Product;" },
        { diff: "Super Ultra", title: "Top Territories", text: "Find the top 3 territories with the highest total sales revenue. Return territorydescription and TotalSales.", sql: "SELECT t.territorydescription, SUM(od.unitPrice * od.quantity * (1-discount)) as TotalSales FROM Territory t JOIN EmployeeTerritory et ON t.territoryCode = et.territoryCode JOIN SalesOrder o ON et.employeeId = o.employeeId JOIN OrderDetail od ON o.entityId = od.orderId GROUP BY t.territoryCode ORDER BY TotalSales DESC LIMIT 3;" },
        { diff: "Super Ultra", title: "Time Between Orders", text: "Use a window function to show the current orderDate and the previous orderDate for the customer with entityId = 1.", sql: "SELECT entityId as OrderId, orderDate as CurrentOrderDate, LAG(orderDate) OVER (ORDER BY orderDate) as PreviousOrderDate FROM SalesOrder WHERE customerId = 1;" },

        { diff: "Super Ultra Hard", title: "Org Chart Depth", text: "Using a recursive CTE on the Employee hierarchy (mgrId), find the maximum depth from any root employee (no manager) down to a leaf. Return a single column MaxDepth.", sql: "WITH RECURSIVE chain AS (\n  SELECT entityId, mgrId, 1 AS depth FROM Employee WHERE mgrId IS NULL\n  UNION ALL\n  SELECT e.entityId, e.mgrId, c.depth + 1\n  FROM Employee e JOIN chain c ON e.mgrId = c.entityId\n)\nSELECT MAX(depth) AS MaxDepth FROM chain;" },
        { diff: "Super Ultra Hard", title: "Top Decile Spenders", text: "Customers in the top 10% by lifetime revenue (use PERCENT_RANK on revenue after discounts). Return companyName and TotalRev for each such customer, highest revenue first.", sql: "WITH cust AS (\n  SELECT c.entityId, c.companyName,\n    SUM(od.unitPrice * od.quantity * (1 - od.discount)) AS TotalRev\n  FROM Customer c\n  JOIN SalesOrder o ON c.entityId = o.customerId\n  JOIN OrderDetail od ON o.entityId = od.orderId\n  GROUP BY c.entityId\n),\nranked AS (\n  SELECT companyName, TotalRev, PERCENT_RANK() OVER (ORDER BY TotalRev) AS pr FROM cust\n)\nSELECT companyName, TotalRev FROM ranked WHERE pr >= 0.9 ORDER BY TotalRev DESC;" },
        { diff: "Super Ultra Hard", title: "Longest Order Silence", text: "Across all customers, what is the largest gap in days between two consecutive orders for the same customer? Use LAG on orderDate partitioned by customerId. Return one column MaxGapDays.", sql: "WITH ord AS (\n  SELECT customerId, orderDate,\n    JULIANDAY(orderDate) - JULIANDAY(LAG(orderDate) OVER (PARTITION BY customerId ORDER BY orderDate)) AS gapDays\n  FROM SalesOrder\n)\nSELECT MAX(gapDays) AS MaxGapDays FROM ord WHERE gapDays IS NOT NULL;" },
        { diff: "Super Ultra Hard", title: "Supplier Category Breadth", text: "Which supplier supplies products in the most distinct categories? Return companyName and CategoryCount (number of distinct categoryIds among their products).", sql: "SELECT s.companyName, COUNT(DISTINCT p.categoryId) AS CategoryCount\nFROM Supplier s\nJOIN Product p ON p.supplierId = s.entityId\nGROUP BY s.entityId\nORDER BY CategoryCount DESC\nLIMIT 1;" },
        { diff: "Super Ultra Hard", title: "Two-Year Loyalists", text: "Customers who placed at least one order in calendar year 2006 and at least one in 2007 (use strftime on orderDate). Return companyName only, sorted alphabetically, using INTERSECT.", sql: "SELECT c.companyName\nFROM Customer c\nJOIN SalesOrder o ON c.entityId = o.customerId\nWHERE strftime('%Y', o.orderDate) = '2006'\nINTERSECT\nSELECT c.companyName\nFROM Customer c\nJOIN SalesOrder o ON c.entityId = o.customerId\nWHERE strftime('%Y', o.orderDate) = '2007'\nORDER BY companyName;" },

        { diff: "Super Ultra Hard Max", title: "Empire Builder", text: "Among employees with no manager (mgrId IS NULL), whose reporting subtree is largest? Use a recursive CTE: each row carries root id; count rows per root. Return RootEmployeeId and TeamSize (include the root in the count).", sql: "WITH RECURSIVE tree AS (\n  SELECT entityId, mgrId, entityId AS root FROM Employee WHERE mgrId IS NULL\n  UNION ALL\n  SELECT e.entityId, e.mgrId, t.root\n  FROM Employee e JOIN tree t ON e.mgrId = t.entityId\n)\nSELECT root AS RootEmployeeId, COUNT(*) AS TeamSize FROM tree GROUP BY root ORDER BY TeamSize DESC LIMIT 1;" },
        { diff: "Super Ultra Hard Max", title: "Breakout Month", text: "Compute monthly revenue (sum of line totals after discounts) by calendar month. Then compare each month to the previous month (LAG). Which month had the largest positive month-over-month change? Return ym (YYYY-MM) and MoMChange.", sql: "WITH monthly AS (\n  SELECT strftime('%Y-%m', o.orderDate) AS ym,\n    SUM(od.unitPrice * od.quantity * (1 - od.discount)) AS rev\n  FROM SalesOrder o\n  JOIN OrderDetail od ON o.entityId = od.orderId\n  WHERE o.orderDate IS NOT NULL\n  GROUP BY strftime('%Y-%m', o.orderDate)\n),\nchg AS (\n  SELECT ym,\n    rev - LAG(rev) OVER (ORDER BY ym) AS MoMChange\n  FROM monthly\n)\nSELECT ym, MoMChange FROM chg WHERE MoMChange IS NOT NULL ORDER BY MoMChange DESC LIMIT 1;" },
        { diff: "Super Ultra Hard Max", title: "Whale Line Item", text: "Which single customer–product pair has the highest total quantity ordered across all lines? Return companyName, productName, and UnitsSold (sum of quantity).", sql: "SELECT c.companyName, p.productName,\n  SUM(od.quantity) AS UnitsSold\nFROM Customer c\nJOIN SalesOrder o ON c.entityId = o.customerId\nJOIN OrderDetail od ON o.entityId = od.orderId\nJOIN Product p ON od.productId = p.entityId\nGROUP BY c.entityId, p.entityId\nORDER BY UnitsSold DESC\nLIMIT 1;" },
        { diff: "Super Ultra Hard Max", title: "Category Omnivores", text: "Find customers who have purchased at least one product from every category (relational division). Use nested NOT EXISTS: there is no category lacking an order from that customer. Return companyName sorted alphabetically.", sql: "SELECT c.companyName\nFROM Customer c\nWHERE NOT EXISTS (\n  SELECT 1 FROM Category cat\n  WHERE NOT EXISTS (\n    SELECT 1 FROM SalesOrder o\n    JOIN OrderDetail od ON o.entityId = od.orderId\n    JOIN Product p ON od.productId = p.entityId\n    WHERE o.customerId = c.entityId AND p.categoryId = cat.entityId\n  )\n)\nORDER BY companyName;" },
        { diff: "Super Ultra Hard Max", title: "Basket Buddies", text: "Which pair of distinct products (by productId, use od1.productId < od2.productId) appears together in the same order line items most often? Return ProductA, ProductB (productName), and TogetherCount.", sql: "SELECT p1.productName AS ProductA, p2.productName AS ProductB, COUNT(*) AS TogetherCount\nFROM OrderDetail od1\nJOIN OrderDetail od2 ON od1.orderId = od2.orderId AND od1.productId < od2.productId\nJOIN Product p1 ON od1.productId = p1.entityId\nJOIN Product p2 ON od2.productId = p2.entityId\nGROUP BY od1.productId, od2.productId\nORDER BY TogetherCount DESC\nLIMIT 1;" },

        { diff: "Super Ultra Hard Max Pro", title: "Revenue Share Titan", text: "Which employee accounts for the largest share of all company revenue (after discounts)? Sum line revenue per employeeId from SalesOrder and OrderDetail; divide by grand total. Return EmployeeName (firstname || ' ' || lastname) and PctOfTotal (fraction 0–1).", sql: "WITH emp_rev AS (\n  SELECT e.entityId, SUM(od.unitPrice * od.quantity * (1 - od.discount)) AS rev\n  FROM Employee e\n  JOIN SalesOrder o ON e.entityId = o.employeeId\n  JOIN OrderDetail od ON o.entityId = od.orderId\n  GROUP BY e.entityId\n),\ntot AS (SELECT SUM(rev) AS total FROM emp_rev)\nSELECT e.firstname || ' ' || e.lastname AS EmployeeName, er.rev * 1.0 / tot.total AS PctOfTotal\nFROM emp_rev er\nJOIN Employee e ON er.entityId = e.entityId\nCROSS JOIN tot\nORDER BY PctOfTotal DESC\nLIMIT 1;" },
        { diff: "Super Ultra Hard Max Pro", title: "Whale Average Ticket", text: "Among customers with more than 5 distinct orders, who has the highest average order value (total discounted revenue divided by number of orders)? Return companyName, orderCnt, and AvgOrderValue.", sql: "WITH cust_stats AS (\n  SELECT c.entityId, c.companyName,\n    COUNT(DISTINCT o.entityId) AS orderCnt,\n    SUM(od.unitPrice * od.quantity * (1 - od.discount)) AS totalRev\n  FROM Customer c\n  JOIN SalesOrder o ON c.entityId = o.customerId\n  JOIN OrderDetail od ON o.entityId = od.orderId\n  GROUP BY c.entityId\n  HAVING COUNT(DISTINCT o.entityId) > 5\n)\nSELECT companyName, orderCnt, totalRev * 1.0 / orderCnt AS AvgOrderValue\nFROM cust_stats\nORDER BY AvgOrderValue DESC\nLIMIT 1;" },
        { diff: "Super Ultra Hard Max Pro", title: "Price Chaos Category", text: "Which product category has the widest spread between its cheapest and most expensive product (MAX(unitPrice) − MIN(unitPrice))? Return categoryName and PriceSpread.", sql: "SELECT c.categoryName, MAX(p.unitPrice) - MIN(p.unitPrice) AS PriceSpread\nFROM Category c\nJOIN Product p ON p.categoryId = c.entityId\nGROUP BY c.entityId, c.categoryName\nORDER BY PriceSpread DESC\nLIMIT 1;" },
        { diff: "Super Ultra Hard Max Pro", title: "Freight Nation", text: "Which shipCountry has the highest total freight billed across all orders? Return shipCountry and TotalFreight (SUM of freight).", sql: "SELECT shipCountry, SUM(freight) AS TotalFreight\nFROM SalesOrder\nWHERE shipCountry IS NOT NULL\nGROUP BY shipCountry\nORDER BY TotalFreight DESC\nLIMIT 1;" },
        { diff: "Super Ultra Hard Max Pro", title: "New Blood 2008", text: "Customers who have at least one order in 2008 but have no orders in 2006. Use EXCEPT (or equivalent). Return companyName only, sorted alphabetically.", sql: "SELECT DISTINCT c.companyName\nFROM Customer c\nJOIN SalesOrder o ON c.entityId = o.customerId\nWHERE strftime('%Y', o.orderDate) = '2008'\nEXCEPT\nSELECT DISTINCT c.companyName\nFROM Customer c\nJOIN SalesOrder o ON c.entityId = o.customerId\nWHERE strftime('%Y', o.orderDate) = '2006'\nORDER BY companyName;" },

        { diff: "Super Ultra Hard Max Pro God", title: "Cross-Border Fulfillment Exposure", text: "Enterprise trade-compliance style metric: sum discounted line revenue (unitPrice × quantity × (1−discount)) for every order line where the product supplier’s country (Supplier.country) is NOT equal to the order’s destination country (SalesOrder.shipCountry). Join OrderDetail → SalesOrder → Product → Supplier. Return one column CrossBorderRevenue.", sql: "SELECT SUM(od.unitPrice * od.quantity * (1 - od.discount)) AS CrossBorderRevenue\nFROM OrderDetail od\nJOIN SalesOrder o ON od.orderId = o.entityId\nJOIN Product p ON od.productId = p.entityId\nJOIN Supplier s ON p.supplierId = s.entityId\nWHERE s.country != o.shipCountry;" },
        { diff: "Super Ultra Hard Max Pro God", title: "Domestic Sourcing Champion", text: "Among all order lines, consider only rows where supplier country equals the bill-to customer’s country (join Customer on SalesOrder.customerId). Aggregate discounted revenue by Category. Which categoryName has the highest DomesticSupplyRevenue? Return categoryName and DomesticSupplyRevenue. Tables: OrderDetail, SalesOrder, Customer, Product, Supplier, Category.", sql: "SELECT c.categoryName, SUM(od.unitPrice * od.quantity * (1 - od.discount)) AS DomesticSupplyRevenue\nFROM OrderDetail od\nJOIN SalesOrder o ON od.orderId = o.entityId\nJOIN Customer cu ON o.customerId = cu.entityId\nJOIN Product p ON od.productId = p.entityId\nJOIN Supplier s ON p.supplierId = s.entityId\nJOIN Category c ON p.categoryId = c.entityId\nWHERE s.country = cu.country\nGROUP BY c.entityId, c.categoryName\nORDER BY DomesticSupplyRevenue DESC\nLIMIT 1;" },
        { diff: "Super Ultra Hard Max Pro God", title: "Category YoY Acceleration", text: "Build yearly discounted revenue by category (strftime year on orderDate). Self-join 2007 vs 2008 rows per category and compute YoYGrowth = (rev2008 − rev2007) / NULLIF(rev2007,0). Which category has the highest YoYGrowth? Return categoryName and YoYGrowth.", sql: "WITH cat_year AS (\n  SELECT c.entityId, c.categoryName, strftime('%Y', o.orderDate) AS yr,\n    SUM(od.unitPrice * od.quantity * (1 - od.discount)) AS rev\n  FROM Category c\n  JOIN Product p ON p.categoryId = c.entityId\n  JOIN OrderDetail od ON p.entityId = od.productId\n  JOIN SalesOrder o ON od.orderId = o.entityId\n  WHERE o.orderDate IS NOT NULL\n  GROUP BY c.entityId, strftime('%Y', o.orderDate)\n)\nSELECT c1.categoryName, (c2.rev - c1.rev) * 1.0 / NULLIF(c1.rev, 0) AS YoYGrowth\nFROM cat_year c1\nJOIN cat_year c2 ON c1.entityId = c2.entityId AND c1.yr = '2007' AND c2.yr = '2008'\nORDER BY YoYGrowth DESC\nLIMIT 1;" },
        { diff: "Super Ultra Hard Max Pro God", title: "Franco–German Corridor Coverage", text: "Sales operations KPI: list employees (firstname || ' ' || lastname as EmployeeName) who have processed at least one order shipping to France AND at least one order shipping to Germany (same employee, any orders). Use INTERSECT on the two sets. Join Employee to SalesOrder on employeeId. Sort by EmployeeName.", sql: "SELECT e.firstname || ' ' || e.lastname AS EmployeeName\nFROM Employee e\nJOIN SalesOrder o ON o.employeeId = e.entityId\nWHERE o.shipCountry = 'France'\nINTERSECT\nSELECT e.firstname || ' ' || e.lastname\nFROM Employee e\nJOIN SalesOrder o ON o.employeeId = e.entityId\nWHERE o.shipCountry = 'Germany'\nORDER BY EmployeeName;" },
        { diff: "Super Ultra Hard Max Pro God", title: "Category Revenue Concentration", text: "For each category, compute each product’s share of that category’s total discounted revenue (two CTEs: lineRev per product, then catTotal per category). Which product has the highest ShareOfCategory (lineRev / catTotal) globally? Return categoryName, productName, ShareOfCategory.", sql: "WITH prod_rev AS (\n  SELECT c.entityId AS cid, c.categoryName, p.entityId AS pid, p.productName,\n    SUM(od.unitPrice * od.quantity * (1 - od.discount)) AS lineRev\n  FROM Category c\n  JOIN Product p ON p.categoryId = c.entityId\n  JOIN OrderDetail od ON p.entityId = od.productId\n  JOIN SalesOrder o ON od.orderId = o.entityId\n  GROUP BY c.entityId, p.entityId\n),\ntot AS (\n  SELECT cid, SUM(lineRev) AS catTotal FROM prod_rev GROUP BY cid\n)\nSELECT pr.categoryName, pr.productName, pr.lineRev * 1.0 / t.catTotal AS ShareOfCategory\nFROM prod_rev pr\nJOIN tot t ON pr.cid = t.cid\nORDER BY ShareOfCategory DESC\nLIMIT 1;" }
    ]
};
